### ISSUE TITLE
Upgrades for 1.14

### ISSUE THREAD

**Issue by danj3** [jschneider1207/weather_report#7]
I've submitted a bunch of PRs to get this working on 1.14 and to fix a few problems. The PRs should be taken in order, as they build on each other. They are small as could be made to expedite the review. RSS is broken, but haven't looked into why, the RSS structure may have changed and the parser isn't happy. XML works well though.

**Comment by jschneider1207** [comment]
Thanks for this! It's very much appreciated! I'll publish a new version, might take a sec as idk if the process has changed since I originally did it.

**Comment by jschneider1207** [comment]
@danj3 published 0.3.0! Also mostly figured out whats up with rss. They changed the subdomain for the feeds and also changed the structure of the feed. Oh and they also gave invalid XML for the feed.

Thank you again!
